PROGRAM WT_Perf


   ! This program is a variable speed version of a much-modified
   ! version of the original PROP code by Aerovironment Inc.


USE                                NWTC_Library
USE                                Parameters
USE                                ProgGen
USE                                WTP_Data
USE                                WTP_Subs

IMPLICIT                           NONE

   ! Local declarations.

REAL(ReKi)                      :: TimerBeg                                        ! Timer start time.
REAL(ReKi)                      :: TimerEnd                                        ! Timer end time.


   ! Get date and time.

DateNow = CurDate()
TimeNow = CurTime()


   ! Reopen the console for FORTRAN carriage control.

CALL NWTC_Init

   ! Print out program name, version, and date.

CALL SetProg
CALL DispNVD

   ! Initialize file system.

CALL IOInit


   ! Get input data.

CALL GetData


   ! If appropriate, open the blade-element data file and generate the header.

IF ( WriteBED )  THEN

   CALL OpenFOutFile ( UnBE, TRIM( RootName )//'.bed' )

   WRITE (UnBE,'(A)')  'Blade-element data generated by '//TRIM( ProgName )//TRIM( ProgVer )//' for input file "' &
                       //TRIM( InpFile )//'".'
   WRITE (UnBE,'(A)')  'Generated on '//TRIM( DateNow )//' at '//TRIM( TimeNow )//'.'
   WRITE (UnBE,'(A)')  'Input file title:'
   WRITE (UnBE,'(A)')  '  '//TRIM( RunTitle )
   WRITE (UnBE,'(A)')  ' '

ENDIF

IF (WriteDebug)  THEN

   CALL OpenFOutFile ( UnDB, TRIM( RootName )//'.dbg' )

   WRITE (UnDB,'(A)')  'Non-converged cases data generated by '//TRIM( ProgName )//TRIM( ProgVer )//' for input file "' &
                       //TRIM( InpFile )//'".'
   WRITE (UnDB,'(A)')  'Generated on '//TRIM( DateNow )//' at '//TRIM( TimeNow )//'.'
   WRITE (UnDB,'(A)')  'Input file title:'
   WRITE (UnDB,'(A)')  '  '//TRIM( RunTitle )
   WRITE (UnDB,'(A)')  ' '
   WRITE (UnDB,'(A)')  '    TSR,OmgRPM,PitDeg,AxInd,TanInd,AlfaD,ClLoc,iseg, ISect'
   WRITE (UnDB,'(A)')  ' '

ENDIF



   ! Calculate some constants.

SweptRad = RotorRad*CosCone
SwpRadIn = 1.0/SweptRad
SwptArea = Pi*SweptRad*SweptRad
HalfRho  = 0.5*AirDens

CALL WrScr ( ' ' )


   ! Start timer.

 CALL CPU_TIME ( TimerBeg )


   ! What type of analysis do we do?

IF ( NumCases == 0 )  THEN            ! Do old-style parametric analysis if number of combined cases is zero.

   CALL ParmAnal

ELSE                                  ! Do new-style combined cases.

   CALL CombCase

ENDIF


   ! Stop timer

 CALL CPU_TIME ( TimerEnd )


   ! Close the output files.

CLOSE ( UnOu )

IF ( WriteBED )  CLOSE ( UnBE )
IF ( WriteDebug )  CLOSE ( UnDB )


   ! Display timer if non-zero.

IF ( TimerEnd > 0.0 )  CALL WrScr1 ( ' Main loop used '//TRIM( Flt2LStr( TimerEnd ) )//' seconds of User CPU time.' )


   ! Display the number of solution problems.

IF ( NmCaseNC == 1 )  THEN

   IF ( ConvFlag == 1 )  THEN
      IF ( NCases == 1 )  THEN
         CALL WrScr1 ( ' WARNING: The case analyzed did not fully meet the convergence criterion.  WT_Perf output nines'// &
                       ' instead of approximate values.' )
      ELSE
         CALL WrScr1 ( ' WARNING: Of the '//TRIM( Int2LStr( NCases ) )//  &
                       ' cases analyzed, there was one case where the solution did not fully meet the convergence criterion.  '// &
                       '  WT_Perf output nines for that case instead of approximate values.' )
      ENDIF
   ELSEIF ( ConvFlag == 2 )  THEN
      IF ( NCases == 1 )  THEN
         CALL WrScr1 ( ' WARNING: The case analyzed did not fully meet the convergence criterion.  WT_Perf output NaN'// &
                       ' instead of approximate values.' )
      ELSE
         CALL WrScr1 ( ' WARNING: Of the '//TRIM( Int2LStr( NCases ) )//  &
                       ' cases analyzed, there was one case where the solution did not fully meet the convergence criterion.  '// &
                       '  WT_Perf output NaN for that case instead of approximate values.' )
      ENDIF
   ELSE
      IF ( NCases == 1 )  THEN
         CALL WrScr1 ( ' WARNING: The case analyzed did not fully meet the convergence criterion.  However, WT_Perf used the'// &
                       ' final guess in subsequent calculations.' )
      ELSE
         CALL WrScr1 ( ' WARNING: Of the '//TRIM( Int2LStr( NCases ) )//  &
                       ' cases analyzed, there was one case where the solution did not fully meet the convergence criterion.'// &
                       '  However, WT_Perf used the final guess in subsequent calculations.' )
      ENDIF
   ENDIF

   IF ( Beep .AND. NmCaseFail == 0 )  CALL UsrAlarm

ELSEIF ( NmCaseNC > 1 )  THEN

   IF ( ConvFlag == 1 )  THEN
      CALL WrScr1 ( ' WARNING: Of the '//TRIM( Int2LStr( NCases ) )//' cases analyzed, there were ' &
                    //TRIM( Int2LStr( NmCaseNC ) )//  &
                    ' cases where the solution did not fully meet the convergence criterion.  WT_Perf output nines'// &
                    ' instead of using the final guesses in subsequent calculations.' )
   ELSEIF ( ConvFlag == 2 )  THEN
      CALL WrScr1 ( ' WARNING: Of the '//TRIM( Int2LStr( NCases ) )//' cases analyzed, there were ' &
                    //TRIM( Int2LStr( NmCaseNC ) )//  &
                    ' cases where the solution did not fully meet the convergence criterion.  WT_Perf output NaN'// &
                    ' instead of using the final guesses in subsequent calculations.' )
   ELSE
      CALL WrScr1 ( ' WARNING: Of the '//TRIM( Int2LStr( NCases ) )//' cases analyzed, there were ' &
                    //TRIM( Int2LStr( NmCaseNC ) )// &
                    ' cases where the solution did not fully meet the convergence criterion.  However, WT_Perf used the final'// &
                    ' guesses in subsequent calculations.' )
   ENDIF

   IF ( Beep .AND. NmCaseFail == 0 )  CALL UsrAlarm

ENDIF

IF ( NmCaseFail == 1 )  THEN

   CALL WrScr ( ' ' )

   IF ( NCases == 1 )  THEN
      CALL WrScr1 ( ' The case analyzed failed to find a solution.' )
   ELSE
      CALL WrScr1 ( ' Of the '//TRIM( Int2LStr( NCases ) )// &
            ' cases analyzed, there was one case that failed to find a solution.' )
   ENDIF

ELSEIF ( NmCaseFail > 1 )  THEN

   CALL WrScr ( ' ' )
   CALL WrScr1 ( ' Of the '//TRIM( Int2LStr( NCases ) )//' cases analyzed, there were '//TRIM( Int2LStr( NmCaseFail ) )// &
                ' cases that failed to find a solution.' )

ENDIF


   ! Normal termination.

CALL NormStop


STOP
END PROGRAM WT_Perf
